//This File Is Auto Generated By Process Control
using UnityEngine;
using UnityEngine.UI;

public class UIBeatTipControl : YViewControl
{
	private UIBeatTipView m_View;

	public static EResType GetResType()
	{
		return EResType.UIBeatTip;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIBeatTipView>();
		ShowBg(false);
	}

	public void ShowBg(bool show)
	{
		m_View.ImgBg.SetActive(show);
	}

	public void SetData(bool isHit, bool isTip)
	{
		if (isHit)
		{
			m_View.ImgBeat.color = new Color(0.929f, 0.267f, 0.518f);
		}
		else if (isTip)
		{
			m_View.ImgBeat.color = Color.white;
		}
		else
		{
			m_View.ImgBeat.color = Color.white;
		}
	}

	public void SetData(int beatIndex)
	{
		bool isDebugMode = false;
		if (BeatGameControl.Instance != null)
		{
			isDebugMode = BeatGameControl.Instance.IsDedugMode;
		}
		if (isDebugMode)
		{
			m_View.TxtTip.text = beatIndex.ToString();
			m_View.TxtTip.gameObject.SetActive(true);
		}
		else
		{
			m_View.TxtTip.gameObject.SetActive(false);
		}
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}