//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIBeatResultView : YBaseView
{
	public Text TxtScore;
	public Button BtnEsc;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		TxtScore = viewItemList[0].Target.GetComponent<Text>();
		BtnEsc = viewItemList[1].Target.GetComponent<Button>();
	}
}