//This File Is Auto Generated By Process Control
using UnityEngine;
using UnityEngine.SceneManagement;

public class UIBeatResultControl : YViewControl
{
	private UIBeatResultView m_View;
	private float m_InitTime;
	private bool m_CanClick = false;

	public static EResType GetResType()
	{
		return EResType.UIBeatResult;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIBeatResultView>();
		m_View.BtnEsc.onClick.AddListener(OnBtnEscClick);
		m_InitTime = Time.time;
	}

	private void Update()
	{
		if (!m_CanClick && Time.time - m_InitTime >= 2f)
		{
			m_CanClick = true;
		}
	}

	void OnBtnEscClick()
	{
		if (!m_CanClick) return;
		Asset.TryLoadScene(UISelectControl.ESceneName.GameEntry.ToString());
	}

	public void SetData(int score)
	{
		m_View.TxtScore.text = score.ToString();

		string sceneName = SceneManager.GetActiveScene().name;
		if (System.Enum.TryParse<UISelectControl.ESceneName>(sceneName, out UISelectControl.ESceneName sceneEnum))
		{
			DataLevel dataLevel = DataSystem.Instance.GetDataLevel();
			dataLevel.LevelScoreDict[(int)sceneEnum] = score;
			DataSystem.Instance.SaveDataLevel();
		}
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}