//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIBeatTipView : YBaseView
{
	public Image ImgBeat;
	public Text TxtTip;
	public GameObject ImgBg;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		ImgBeat = viewItemList[0].Target.GetComponent<Image>();
		TxtTip = viewItemList[1].Target.GetComponent<Text>();
		ImgBg = viewItemList[2].Target.gameObject;
	}
}