//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIBeatGuideView : YBaseView
{
	public RectTransform TipRoot;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		TipRoot = viewItemList[0].Target.GetComponent<RectTransform>();
	}
}