//This File Is Auto Generated By Process Control
using UnityEngine;
using UnityEngine.UI;
using System;

public class UICounterControl : YViewControl
{
	private UICounterView m_View;
	private Image[] m_Images;
	private System.Action m_Callback;
	private int m_CurrentIndex = 0;
	private float m_Timer = 0f;
	private const float k_Interval = 1f;
	private bool m_IsPlaying = false;

	public static EResType GetResType()
	{
		return EResType.UICounter;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UICounterView>();
	}

	public void SetData(System.Action callback)
	{
		m_Callback = callback;
		m_Images = new Image[]
		{
			m_View.One,
			m_View.Two,
			m_View.Three,
			m_View.Four,
			m_View.Five
		};

		for (int i = 0; i < m_Images.Length; i++)
		{
			if (m_Images[i] != null)
			{
				m_Images[i].gameObject.SetActive(false);
			}
		}

		m_CurrentIndex = 0;
		m_Timer = 0f;
		m_IsPlaying = true;
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}

	private void Update()
	{
		if (!m_IsPlaying || m_Images == null) return;

		m_Timer += Time.deltaTime;

		if (m_Timer >= k_Interval)
		{
			m_Timer = 0f;

			if (m_CurrentIndex > 0 && m_CurrentIndex <= m_Images.Length)
			{
				if (m_Images[m_CurrentIndex - 1] != null)
				{
					m_Images[m_CurrentIndex - 1].gameObject.SetActive(false);
				}
			}

			if (m_CurrentIndex < m_Images.Length)
			{
				if (m_Images[m_CurrentIndex] != null)
				{
					m_Images[m_CurrentIndex].gameObject.SetActive(true);
				}
				m_CurrentIndex++;
			}

			if (m_CurrentIndex >= m_Images.Length)
			{
				m_IsPlaying = false;
				if (m_Callback != null)
				{
					m_Callback();
				}
				Destroy(gameObject);
			}
		}
	}
}