//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UIIngameRatingView : YBaseView
{
	public Text TxtScore;
	public GameObject ImgScore;
	public RectTransform TutorSoundClose;
	public RectTransform TutorSoundOpen;
	public RectTransform TutorUIClose;
	public RectTransform TutorUIOpen;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		TxtScore = viewItemList[0].Target.GetComponent<Text>();
		ImgScore = viewItemList[1].Target.gameObject;
		TutorSoundClose = viewItemList[2].Target.GetComponent<RectTransform>();
		TutorSoundOpen = viewItemList[3].Target.GetComponent<RectTransform>();
		TutorUIClose = viewItemList[4].Target.GetComponent<RectTransform>();
		TutorUIOpen = viewItemList[5].Target.GetComponent<RectTransform>();
	}
}