//This File Is Auto Generated By Process Control
using UnityEngine;
using UnityEngine.UI;


public class UIIngameRatingControl : YViewControl
{
	private UIIngameRatingView m_View;
	private Image m_ImgScoreComponent;

	public static EResType GetResType()
	{
		return EResType.UIIngameRating;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIIngameRatingView>();
		if (m_View.ImgScore != null)
		{
			m_ImgScoreComponent = m_View.ImgScore.GetComponent<Image>();
		}
	}

	public void SetData()
	{
		DataLevel dataLevel = DataSystem.Instance.GetDataLevel();
		bool useTutorUI = dataLevel.UseTutorUI;
		m_View.TutorUIOpen.gameObject.SetActive(useTutorUI);
		m_View.TutorUIClose.gameObject.SetActive(!useTutorUI);
	}

	public void SetScore(int score)
	{
		m_View.TxtScore.text = score.ToString();
	}

	public void SetImgScore(float scoreValue)
	{
		if (m_ImgScoreComponent == null) return;

		ERatingGrade ratingGrade = DataSystem.GetRatingGrade(scoreValue);
		string spriteName = DataSystem.GetSpriteNameByRating(ratingGrade);
		Sprite sprite = Resources.Load<Sprite>("Arts/common/" + spriteName);
		if (sprite == null)
		{
			sprite = Asset.GetSprite(spriteName);
		}
		if (sprite != null)
		{
			m_ImgScoreComponent.sprite = sprite;
		}
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}