//This File Is Auto Generated By Process Control
using UnityEngine;

public class UISelectTutorControl : YViewControl
{
	private UISelectTutorView m_View;
	private DataLevel m_DataLevel;

	public static EResType GetResType()
	{
		return EResType.UISelectTutor;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UISelectTutorView>();
		m_DataLevel = DataSystem.Instance.GetDataLevel();
		m_View.BtnTutorUI.onClick.AddListener(OnBtnTutorUIClick);
		m_View.BtnTutorSound.onClick.AddListener(OnBtnTutorSoundClick);
		m_View.TutorUIOpen.onClick.AddListener(OnBtnTutorUIClick);
		m_View.TutorUIOff.onClick.AddListener(OnBtnTutorUIClick);
		m_View.TutorSoundOpen.onClick.AddListener(OnBtnTutorSoundClick);
		m_View.TutorSoundOff.onClick.AddListener(OnBtnTutorSoundClick);
	}

	public void OnBtnTutorUIClick()
	{
		Debug.Log("OnBtnTutorUIClick");
		m_DataLevel.UseTutorUI = !m_DataLevel.UseTutorUI;
		ShowTutorUISwitch(m_DataLevel.UseTutorUI);
		DataSystem.Instance.SaveDataLevel();
	}

	public
	 void OnBtnTutorSoundClick()
	{
		Debug.Log("OnBtnTutorSoundClick");
		m_DataLevel.UseTutorSound = !m_DataLevel.UseTutorSound;
		ShowTutorSoundSwitch(m_DataLevel.UseTutorSound);
		DataSystem.Instance.SaveDataLevel();
	}

	public void ShowTutorUISwitch(bool isOn)
	{
		m_View.TutorUIOpen.gameObject.SetActive(isOn);
		m_View.TutorUIOff.gameObject.SetActive(!isOn);
	}

	void ShowTutorSoundSwitch(bool isOn)
	{
		m_View.TutorSoundOpen.gameObject.SetActive(isOn);
		m_View.TutorSoundOff.gameObject.SetActive(!isOn);
	}

	public void SetData()
	{
		ShowTutorUISwitch(m_DataLevel.UseTutorUI);
		ShowTutorSoundSwitch(m_DataLevel.UseTutorSound);
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}