//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UISelectTutorView : YBaseView
{
	public Button BtnTutorUI;
	public Button BtnTutorSound;
	public Button TutorUIOff;
	public GameObject TextName;
	public Button TutorSoundOpen;
	public Button TutorSoundOff;
	public GameObject CloseBonus;
	public Text TxtTip;
	public Button TutorUIOpen;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		BtnTutorUI = viewItemList[0].Target.GetComponent<Button>();
		BtnTutorSound = viewItemList[1].Target.GetComponent<Button>();
		TutorUIOff = viewItemList[2].Target.GetComponent<Button>();
		TextName = viewItemList[3].Target.gameObject;
		TutorSoundOpen = viewItemList[4].Target.GetComponent<Button>();
		TutorSoundOff = viewItemList[5].Target.GetComponent<Button>();
		CloseBonus = viewItemList[6].Target.gameObject;
		TxtTip = viewItemList[7].Target.GetComponent<Text>();
		TutorUIOpen = viewItemList[8].Target.GetComponent<Button>();
	}
}