//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UISelectView : YBaseView
{
	public Button BtnLevel1;
	public Animator Level1;
	public Button BtnLevel2;
	public Animator Level2;
	public Button BtnLevel3;
	public Animator Level3;
	public Button BtnLevel4;
	public Animator Level4;
	public Button BtnSpace;
	public RectTransform Lock1;
	public RectTransform Lock2;
	public RectTransform Lock3;
	public RectTransform Lock4;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		BtnLevel1 = viewItemList[0].Target.GetComponent<Button>();
		Level1 = viewItemList[0].Target.GetComponent<Animator>();
		BtnLevel2 = viewItemList[1].Target.GetComponent<Button>();
		Level2 = viewItemList[1].Target.GetComponent<Animator>();
		BtnLevel3 = viewItemList[2].Target.GetComponent<Button>();
		Level3 = viewItemList[2].Target.GetComponent<Animator>();
		BtnLevel4 = viewItemList[3].Target.GetComponent<Button>();
		Level4 = viewItemList[3].Target.GetComponent<Animator>();
		BtnSpace = viewItemList[4].Target.GetComponent<Button>();
		Lock1 = viewItemList[5].Target.GetComponent<RectTransform>();
		Lock2 = viewItemList[6].Target.GetComponent<RectTransform>();
		Lock3 = viewItemList[7].Target.GetComponent<RectTransform>();
		Lock4 = viewItemList[8].Target.GetComponent<RectTransform>();
	}
}