//This File Is Auto Generated By Process Control
using UnityEngine;

public class UIStartControl : YViewControl
{
	private UIStartView m_View;
	private float m_AnimationDuration;
	private float m_AnimationStartTime;
	private bool m_CanClick = false;

	public static EResType GetResType()
	{
		return EResType.UIStart;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIStartView>();

		AnimatorStateInfo stateInfo = m_View.Canvas.GetCurrentAnimatorStateInfo(0);
		m_AnimationDuration = stateInfo.length;
		m_AnimationStartTime = Time.time;
	}


	private void Update()
	{
		if (!m_CanClick)
		{
			if (Time.time - m_AnimationStartTime >= m_AnimationDuration)
			{
				m_CanClick = true;
			}
			else
			{
				return;
			}
		}

		if (Input.GetKeyDown(KeyCode.Space) || Input.GetMouseButtonDown(0))
		{
			if (DataSystem.Instance.GetDataLevel().LevelUnlocked.Count > 1)
			{
				Asset.TryLoadScene(UISelectControl.ESceneName.GameEntry.ToString());
			}
			else
			{
				Asset.TryLoadScene(UISelectControl.ESceneName.Level04_Sing.ToString());

			}
		}
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}