//This File Is Auto Generated By Process Control
using UnityEngine;

public class UIStartControl : YViewControl
{
	private UIStartView m_View;

	public static EResType GetResType()
	{
		return EResType.UIStart;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UIStartView>();
	}

	public void SetData()
	{
		;
	}

	private void Update()
	{
		if (Input.GetKeyDown(KeyCode.Space))
		{
			if (DataSystem.Instance.GetDataLevel().LevelUnlocked.Count > 1)
			{
				Asset.TryLoadScene(UISelectControl.ESceneName.GameEntry.ToString());
			}
			else
			{
				Asset.TryLoadScene(UISelectControl.ESceneName.Level04_Sing.ToString());

			}
		}
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}