//This File Is Auto Generated By Process Control
using UnityEngine;

public class UISucceedCounterControl : YViewControl
{
	private UISucceedCounterView m_View;
	public int LeftSucceedNum = 3;

	public static EResType GetResType()
	{
		return EResType.UISucceedCounter;
	}

	protected override void OnInit()
	{
		base.OnInit();
		m_View = CreateView<UISucceedCounterView>();
	}

	public void SetData()
	{
		UpdateText();
	}

	public void DecreaseSucceedNum()
	{
		LeftSucceedNum--;
		if (LeftSucceedNum < 0)
		{
			LeftSucceedNum = 0;
		}
		UpdateText();
	}

	private void UpdateText()
	{
		if (m_View != null && m_View.TxtCnt != null)
		{
			m_View.TxtCnt.text = "剩余成功次数:" + LeftSucceedNum;
		}
	}

	private void Update()
	{
		if (LeftSucceedNum == 0)
		{
			Asset.TryLoadScene(UISelectControl.ESceneName.Level04_Sing.ToString());
		}
	}

	protected override void OnReturn()
	{
		base.OnReturn();
	}
}