//This File Is Auto Generated By Process View
using UnityEngine;
using UnityEngine.UI;

public class UISucceedCounterView : YBaseView
{
	public Text TxtCnt;
	public override void OnInit(Transform holder)
	{
		var itemRef = holder.GetComponent<YViewReference>();
		if(itemRef == null) return;
		var viewItemList = itemRef.ViewItemList;
		if(viewItemList == null || viewItemList.Count == 0) return;
		TxtCnt = viewItemList[0].Target.GetComponent<Text>();
	}
}