//This File Is Auto Generated By Process Config
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;

public class DataLevel : IData
{
	public List<int> LevelUnlocked = new List<int>();
	public int TutorNum;
	public void LoadFromJson(JObject jobject)
	{
		JsonUtil.ToList(jobject, "LevelUnlocked", ref LevelUnlocked);
		TutorNum = (int)jobject["TutorNum"];
	}
	public void SaveToJson(JObject jobject)
	{
		jobject.Add("LevelUnlocked", JsonUtil.ToJArray(LevelUnlocked));
		jobject.Add("TutorNum", TutorNum);
	}
	public void AddLevelUnlockedData(int data)
	{
		LevelUnlocked.Add(data);
	}
	public void RemoveLevelUnlockedData(int data)
	{
		LevelUnlocked.Remove(data);
	}
	public int GetLevelUnlockedData(int dataIndex)
	{
		return LevelUnlocked[dataIndex];
	}
}
public partial class DataSystem
{
	DataLevel m_DataLevel;

	public DataLevel GetDataLevel()
	{
		if (m_DataLevel == null)
		{
			m_DataLevel = new DataLevel();
		}
		return m_DataLevel;
	}

	public void SaveDataLevel()
	{
		SaveJsonFile("Data_Level", m_DataLevel);
	}
	public void LoadDataLevel()
	{
		LoadJsonFile("Data_Level", ref m_DataLevel);
	}
}