//This File Is Auto Generated By Process Config
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;

public class DataLevel : IData
{
	public List<int> LevelUnlocked = new List<int>();
	public int TutorUINum;
	public int TutorSoundNum;
	public List<int> LevelScoreArray = new List<int>();
	public bool UseTutorUI;
	public bool UseTutorSound;
	public void LoadFromJson(JObject jobject)
	{
		JsonUtil.ToList(jobject, "LevelUnlocked", ref LevelUnlocked);
		TutorUINum = (int)jobject["TutorUINum"];
		TutorSoundNum = (int)jobject["TutorSoundNum"];
		JsonUtil.ToList(jobject, "LevelScoreArray", ref LevelScoreArray);
		UseTutorUI = (bool)jobject["UseTutorUI"];
		UseTutorSound = (bool)jobject["UseTutorSound"];
	}
	public void SaveToJson(JObject jobject)
	{
		jobject.Add("LevelUnlocked", JsonUtil.ToJArray(LevelUnlocked));
		jobject.Add("TutorUINum", TutorUINum);
		jobject.Add("TutorSoundNum", TutorSoundNum);
		jobject.Add("LevelScoreArray", JsonUtil.ToJArray(LevelScoreArray));
		jobject.Add("UseTutorUI", UseTutorUI);
		jobject.Add("UseTutorSound", UseTutorSound);
	}
	public void AddLevelUnlockedData(int data)
	{
		LevelUnlocked.Add(data);
	}
	public void RemoveLevelUnlockedData(int data)
	{
		LevelUnlocked.Remove(data);
	}
	public int GetLevelUnlockedData(int dataIndex)
	{
		return LevelUnlocked[dataIndex];
	}
	public void AddLevelScoreArrayData(int data)
	{
		LevelScoreArray.Add(data);
	}
	public void RemoveLevelScoreArrayData(int data)
	{
		LevelScoreArray.Remove(data);
	}
	public int GetLevelScoreArrayData(int dataIndex)
	{
		return LevelScoreArray[dataIndex];
	}
}
public partial class DataSystem
{
	DataLevel m_DataLevel;

	public DataLevel GetDataLevel()
	{
		if (m_DataLevel == null)
		{
			m_DataLevel = new DataLevel();
		}
		return m_DataLevel;
	}

	public void SaveDataLevel()
	{
		SaveJsonFile("Data_Level", m_DataLevel);
	}
	public void LoadDataLevel()
	{
		LoadJsonFile("Data_Level", ref m_DataLevel);
	}
}